# Generated by Django 3.2.6 on 2021-08-22 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
