# Generated by Django 3.2.6 on 2021-08-22 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20210822_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.EmailValidator(message='Email wrong')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(code='invalid Phone format', message='Phone Number must be in +XXXXXXXXXXX format', regex='^[0-9\\-\\+]{9,15}$')]),
        ),
    ]
